### ISSUE TITLE
Is there a publicly visible URL to ballots? 

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/it-transformation#121]
Under Kavi, we had an internal link that only members could see and use to vote and a publicly visible link that would make the ballot visible to non-TC/OASIS members. This was part of our openness commitment. 

I just opened a ballot for UBL and I don't see a way to make the ballot visible publicly. Do we have a way to do this. It is important.

**Comment by KellyCul** [comment]
Yes -- that link is here. It is visible in the logged out view in the quick links toolbar on the left side of the page.

https://groups.oasis-open.org/higherlogic/ws/public/documents?view=
