### ISSUE TITLE
Formatting Issue for Discussions

### ISSUE THREAD

**Issue by KellyCul** [oasis-dev/it-transformation#142]
Reported by: Patrick Durusu

The formatting is a mess for their minutes.
https://groups.oasis-open.org/discussion/draft-minutes-for-4-march-2024

**Comment by OASIS-OP-Admin** [comment]
Patrick is using some tool where HL does not recognize the formatting. HL says there is nothing we can do about this. Thir suggestion was for him to copy/paste into something that will strip the formatting. And then copy/paste into an email for sending to the TC. 

Patrick was informed of this and not thrilled with the idea.
