### ISSUE TITLE
Comment List Homepage not visible when logged out

### ISSUE THREAD

**Issue by KellyCul** [oasis-dev/it-transformation#176]
Reported by: Rodolfo Reyes  - XLIFF

Sent to HL. Your case ([#405695](https://support.higherlogic.com/hc/requests/405695))

**Comment by OASIS-OP-Admin** [comment]
Make sure the comment homepage in HL is visible without being logged in
From admin panel > Community > List > search for tc > orange edit button > 
view permission set to Public > save
Join Permissions > Authenticated > save


HL Staff also adjusted global settings so pages should be visible when logged out and incognito. Kelly tested this and it seems to work.
