### ISSUE TITLE
Can we remove the blue Create button on the far right, next to the avatar buttons

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/it-transformation#78]
Clicking on that button gives 3 options: Discussion thread, Library entry, and Blog post. Since we have hidden all 3 features for now, the button is a back door to the features. Can we remove it?

**Comment by scottmcgrath** [comment]
It is removed - but I don'y know what I did to do so.

Please confirm ity is gone, and report if you think you did somethinhg to make it happen

**Comment by scottmcgrath** [comment]
Kelly reports its gone
