### ISSUE TITLE
Set up a profile

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/it-transformation#8]
### Goal
As an interested person or participant, I want to be able to go to a web page where I can set up an account for myself and provide useful information (name, email, GH id, employer), so that I can be subscribed to resources of projects (e.g. calendars, email lists) that interest me and participate in Open Projects.

### Additional details
- Please provide any more information about what you want to happen here or describe it as a problem (e.g. I'm always frustrated when [...]).

### Notes
Please provide relevant information
- details
- context
- related issues

**Comment by OASIS-OP-Admin** [comment]
John Wolpert mocked up an example using Signup Genius. Can be found at https://www.signupgenius.com/org/baseline#/

**Comment by scottmcgrath** [comment]
Wolperts mockup no longer available

**Comment by scottmcgrath** [comment]
Persons profile to be set up in SF as primary data source to push out to various tools.  Resource tools - Repos, mail lists etc will be handled by specific tools

No general all tool roll-up view of available resources is expected in this dev cycle.
