### ISSUE TITLE
Documents can't be downloaded

### ISSUE THREAD

**Issue by scottmcgrath** [oasis-dev/it-transformation#80]
I can get links, but the download fails
https://oasis.connectedcommunity.org/higherlogic/ws/groups/1a8eb9f9-fe84-4dba-9ec1-018dc7d3f26c/download/67638/latest

Error text: 

The document file for 'amqp-bindmap-jms-v1.0-wd10.pdf' could not be found. Please contact the site administrator and report this error

**Comment by OASIS-OP-Admin** [comment]
I just tried on several TCs and I confirm that the download is not working.

**Comment by OASIS-OP-Admin** [comment]
I just uploaded a file to the dev-test TC. It loaded successfully and then downloaded successfully. There must be something about the migration of existing documents that is configured wrong

**Comment by scottmcgrath** [comment]
confirmed can now download
