### ISSUE TITLE
What will the URLs be TCs after launch? 

### ISSUE THREAD

**Issue by OASIS-OP-Admin** [oasis-dev/it-transformation#82]
In kavi, we had www.oasis-open.org/committees/tc-name for the public view and ...apps/workgroup/something... for the internal view. On connectedcommunities.org, I'm seeing urls like https://oasis.connectedcommunity.org/higherlogic/ws/groups/e994955e-ffdc-4804-8430-018dc7d3ef6b/documents

is that the url form we'll see from now on or will it be something more comprehensible?

**Comment by scottmcgrath** [comment]
Modern web systems use GUIDs, not simple human-readable structured URLs thta we know and love.  That gobblygook in the middle is the GUID

As a placeholder, the table of building blocks in the conversions of old url --> new url and old mailing list --> new mail address is in the shared folder. https://docs.google.com/spreadsheets/d/1TxuhhvqvMGSgloqJ8_DX4bdfYm-IjOH7nshX-s8ulDU/edit?usp=sharing
